# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - 3.2
  - 3.3
  - oldrel
  - release

# devel have issues to install devtools
matrix:
  - r: devel
    warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
