# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - release

# devel have issues to install devtools
matrix:
  - r: devel
    os: linux
    warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
